export default {
  INVALIDATE_DOCUMENTS: 'INVALIDATE_DOCUMENTS',
  REQUEST_DOCUMENTS: 'REQUEST_DOCUMENTS',
  RECEIVE_DOCUMENTS: 'RECEIVE_DOCUMENTS',
  RECEIVE_DOCUMENTS_ERROR: 'RECEIVE_DOCUMENTS_ERROR',

  REQUEST_DOCUMENT: 'REQUEST_DOCUMENT',
  RECEIVE_DOCUMENT: 'RECEIVE_DOCUMENT',
  RECEIVE_DOCUMENT_ERROR: 'RECEIVE_DOCUMENT_ERROR',

  REQUEST_UPDATE_DOCUMENT: 'REQUEST_UPDATE_DOCUMENT',
  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  UPDATE_DOCUMENT_ERROR: 'UPDATE_DOCUMENT_ERROR',

  NEW_DOCUMENT_REQUEST: 'NEW_DOCUMENT_REQUEST',
  NEW_DOCUMENT: 'NEW_DOCUMENT'
};
