export default {
  ADD_PROJECT: 'ADD_PROJECT',
  REQUEST_PROJECTS: 'REQUEST_PROJECTS',
  RECEIVE_PROJECTS: 'RECEIVE_PROJECTS',
  RECEIVE_PROJECTS_ERROR: 'RECEIVE_PROJECTS_ERROR',
  INVALIDATE_PROJECTS: 'INVALIDATE_PROJECTS',

  NEW_PROJECT_REQUEST: 'NEW_PROJECT_REQUEST',
  NEW_PROJECT: 'NEW_PROJECT',

  UPDATE_PROJECT_REQUEST: 'UPDATE_PROJECT_REQUEST',
  UPDATE_PROJECT_ERROR: 'UPDATE_PROJECT_ERROR',
  UPDATE_PROJECT: 'UPDATE_PROJECT'
};
