// @flow
export default {
  ADD_CAMPAIGN: 'ADD_CAMPAIGN',
  REQUEST_CAMPAIGNS: 'REQUEST_CAMPAIGNS',
  RECEIVE_CAMPAIGNS: 'RECEIVE_CAMPAIGNS',
  RECEIVE_CAMPAIGNS_ERROR: 'RECEIVE_CAMPAIGNS_ERROR',
  INVALIDATE_CAMPAIGNS: 'INVALIDATE_CAMPAIGNS',

  NEW_CAMPAIGN_REQUEST: 'NEW_CAMPAIGN_REQUEST',
  NEW_CAMPAIGN_ERROR: 'NEW_CAMPAIGN_ERROR',
  NEW_CAMPAIGN: 'NEW_CAMPAIGN',

  UPDATE_CAMPAIGN_REQUEST: 'UPDATE_CAMPAIGN_REQUEST',
  UPDATE_CAMPAIGN_ERROR: 'UPDATE_CAMPAIGN_ERROR',
  UPDATE_CAMPAIGN: 'UPDATE_CAMPAIGN',

  REMOVE_CAMPAIGN_REQUEST: 'REMOVE_CAMPAIGN_REQUEST',
  REMOVE_CAMPAIGN_ERROR: 'REMOVE_CAMPAIGN_ERROR',
  REMOVE_CAMPAIGN: 'REMOVE_CAMPAIGN',

  SWITCH_CAMPAIGN_REQUEST: 'SWITCH_CAMPAIGN_REQUEST',
  SWITCH_CAMPAIGN: 'SWITCH_CAMPAIGN',
  SWITCH_CAMPAIGN_ERROR: 'SWITCH_CAMPAIGN_ERROR'
};
